### ISSUE TITLE
A “key ‘ViewLayer’ not found'” error occurs.

### ISSUE THREAD

**Issue by umiyuki** [Shaamallow/texture-diffusion#12]
Windows 10, using Blender 4.2.2.
When I press the Generate button to generate an image, I get the following error In my environment, the default view layer is named “View Layer” (with spaces), and if I rename it to “ViewLayer” (without spaces), the error disappears.

<details>
  <summary>Error code</summary>
  
諠・ｱ: Camera 1 has been setup and aligned to view
繧ｨ繝ｩ繝ｼ: Python: Traceback (most recent call last):
  File "C:\Users\test\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\blender_texture_diffusion\src\operators\generation_operators.py", line 527, in execute
    bpy.ops.diffusion.render_depth(uuid=generation_uuid)
  File "C:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: 繧ｨ繝ｩ繝ｼ: Python: Traceback (most recent call last):
  File "C:\Users\test\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\blender_texture_diffusion\src\operators\image_render_operators.py", line 113, in execute
    bpy.context.scene.view_layers["ViewLayer"].use_pass_z = True
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'bpy_prop_collection[key]: key "ViewLayer" not found'
菴咲ｽｮ・咾:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts\modules\bpy\ops.py:109
  
</details>

**Comment by Shaamallow** [comment]
Thank you for noticing that. I'll try to access it differently then
